development:
  adapter: postgresql
  encoding: unicode
  database: synesthetic_development
  pool: 5
  username: synesthetic
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: synesthetic_test
  pool: 5
  username: synesthetic
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: synesthetic_production
  pool: 5
  username: synesthetic
  password:
